### ISSUE TITLE
Fix README typos

### ISSUE THREAD

**Issue by vinn946** [appvia/artefactor#45]
changes needed to [update-image-vars](https://github.com/appvia/artefactor#update-image-vars)

- `ARTEFACTOR_PRIVATE_REGISTRY` should be renamed to `ARTEFACTOR_DOCKER_REGISTRY`
- Images should be exported with `eval "${exports}"` rather than `eval "echo ${exports}"`

**Comment by lewismarshall** [comment]
Also see ???:
```
| `--docker-username` | `usernmame` | A valid docker registry user-name see # | `bob` |
```
