### ISSUE TITLE
Running artefactor save with defaults fails due to unclean git repo

### ISSUE THREAD

**Issue by janakerman** [appvia/artefactor#93]
Following the example (and simplifying it a little) I package a single git repository:
`artefactor save --git-repos .`

This results in the archive being made in `./downloads` - relative to the work dir (the git repo). The checksum / metadata / artefactor binary are saved here, and the net effect is that the repository is no longer clean & packaging fails.

    artefactor save --git-repos .
    Saving meta-data and me
    updating checksum for downloads/saveDir.meta
    updating checksum for downloads/artefactor_linux_amd64
    updating checksum for downloads/artefactor_linux_amd64.binmark.meta
    
    Saving git repos
    Archiving git repo .
    Error: problem saving git repository . to directory downloads:Not backing up git directory .- not clean:
    ?? downloads/artefactor_linux_amd64
    ?? downloads/artefactor_linux_amd64.binmark.meta
    ?? downloads/checksum.txt
    ?? downloads/saveDir.meta

Version:
{Version:v1.0.0 Sha:27f9db7278790d56b9ec67d160670ce30b6825e2}

**Comment by KashifSaadat** [comment]
Hi Jan, this is expected behaviour. If you are archiving the current directory (git repository) and using default options, then `downloads` should be added to your `.gitignore` file. Otherwise you can specify an alternate directory with the `--archive-dir <path>` flag.
